name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]

    steps:
      - name: Setup Repo
        uses: actions/checkout@v4

      - name: Uses node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn install --immutable

      - name: Seutp
        run: yarn compile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test